#cloud-config
package_update: true
package_upgrade: true
fqdn: caltechdata.local
packages:
  - sshfs
  - build-essential
  - git
  - snapcraft
  - curl
  - python2
  - python3-dev
  - python-is-python3
  - python3-pip
  - rsync
  - nginx
  - imagemagick
  - pkg-config
  - libxml2-dev
  - libxmlsec1-dev
  - docker.io
  - docker-compose
  - makepasswd
  - shellcheck
groups:
  - docker
  - staff
  - www-data
snap:
  commands:
  - [ install, --classic, certbot ]
runcmd:
  - adduser ubuntu docker
  - adduser ubuntu staff
  - adduser ubuntu www-data
  - [ python3, -m, pip, install, invenio-cli ]
