#cloud-config
package_update: true
package_upgrade: true
packages:
  - build-essential
  - git
  - snapcraft
  - curl 
  - python3-dev
  - python3-pip
  - rsync
  - nginx 
  - imagemagick
  - libxml2-dev
  - libxmlsec1-dev
groups:
  - docker
  - staff
  - www-data
snap:
  commands:
  - [ install, docker ]
  - [ install, certbot ]
runcmd:
  - adduser ubuntu docker
  - adduser ubuntu staff
  - adduser ubuntu www-data
  - [ python3, -m, pip, install, invenio-cli ]
