#cloud-config
package_update: true
package_upgrade: true
fqdn: dev-gui.local
packages:
  - aptitude
  - sshfs
  - build-essential
  - git
  - snapcraft
  - autoconf
  - automake
  - cmake
  - curl
  - wget
  - tmux
  - tree
  - htop
  - elinks
  - lynx
  - python3-dev
  - python3-pip
  - python-is-python3
  - pandoc
  - rsync
  - libexpat1
  - xrdp
  - ubuntu-desktop
  - makepasswd
  - shellcheck
  - aspell
  - aspell-en
groups:
  - docker
  - staff
  - www-data
snap:
  commands:
  - [ install, docker ]
  - [ install, --classic, go ]
runcmd:
  - adduser ubuntu docker
  - adduser ubuntu staff
  - adduser ubuntu www-data
