#cloud-config
package_update: true
package_upgrade: true
fqdn: dev.local
packages:
  - sshfs
  - build-essential
  - git
  - snapcraft
  - autoconf
  - automake
  - curl
  - wget
  - tmux
  - tree
  - htop
  - lynx
  - python3-dev
  - python3-pip
  - python-is-python3
  - pandoc
  - rsync
  - libexpat1
  - mysql-server-8.0
  - apache2
  - apache2-utils
  - ssl-cert
  - libapache2-mod-wsgi
  - makepasswd
  - shellcheck
groups:
  - docker
  - staff
  - www-data
snap:
  commands:
  - [ install, docker ]
  - [ install, --classic, go ]
  - [ install, datatools ]
  - [ install, mkpage ]
  - [ install, eprinttools ]
  - [ install, dataset ]
runcmd:
  - adduser ubuntu docker
  - adduser ubuntu staff
  - adduser ubuntu www-data
