#cloud-config
package_update: true
package_upgrade: true
fqdn: invenio-rdm.local
packages:
  - build-essential
  - git
  - lynx
  - tmux
  - curl 
  - python2
  - python3-dev
  - python3-pip
  - python-is-python3
  - rsync
  - nginx
  - libcairo2-dev
  - imagemagick
  - libxml2-dev
  - libxmlsec1-dev
  - docker.io
  - docker-compose
groups:
  - docker
  - staff
  - www-data
runcmd:
  - adduser ubuntu docker
  - adduser ubuntu staff
  - adduser ubuntu www-data
  - [ python3, -m, pip, install, invenio-cli ]
