#cloud-config
package_update: true
package_upgrade: true
fqdn: invenio-rdm.local
packages:
  - sshfs
  - build-essential
  - git
  - lynx
  - tmux
  - curl
  - python3-dev
  - python3-pip
  - rsync
  - nginx
  - imagemagick
  - pkg-config
  - libxml2-dev
  - libxmlsec1-dev
  - docker.io
  - docker-compose
  - makepasswd
  - shellcheck
groups:
  - docker
  - staff
  - www-data
runcmd:
  - adduser ubuntu docker
  - adduser ubuntu staff
  - adduser ubuntu www-data
  - [ python3, -m, pip, install, invenio-cli ]
