#cloud-config
package_update: true
package_upgrade: true
fqdn: invenio-rdm.local
apt:
  preserve_sources_list: false
  sources:
    deadsnakes-ppa:
      source: ppa:deadsnakes/ppa
packages:
  - sshfs
  - build-essential
  - git
  - lynx
  - tmux
  - curl
  - python2
  - python3-dev
  - python3-pip
  - python3.9
  - rsync
  - nginx
  - imagemagick
  - pkg-config
  - libxml2-dev
  - libxmlsec1-dev
  - docker.io
  - docker-compose
  - makepasswd
  - shellcheck
groups:
  - docker
  - staff
  - www-data
runcmd:
  - adduser ubuntu docker
  - adduser ubuntu staff
  - adduser ubuntu www-data
  - [ python3, -m, pip, install, invenio-cli ]
